# Generated by Django 4.2.23 on 2025-07-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_usersubscription_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usersubscription'),
            preserve_default=False,
        ),
    ]
