# Generated by Django 4.2.23 on 2025-07-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription',
        ),
    ]
