# Generated by Django 4.2.23 on 2025-07-13 21:10

from django.db import migrations, models
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='begin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end',
            field=models.DateTimeField(default=subscriptions.models.default_end),
        ),
    ]
