# Generated by Django 4.2.23 on 2025-07-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_count_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
